// flow-typed signature: 578d0ececbb3bf9efd72fffccec6f9b9
// flow-typed version: <<STUB>>/jest-mock-console_v^1.0.0/flow_v0.105.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-mock-console'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-mock-console' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-mock-console/dist' {
  declare module.exports: any;
}

declare module 'jest-mock-console/dist/setupTestFramework' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-mock-console/dist/index' {
  declare module.exports: $Exports<'jest-mock-console/dist'>;
}
declare module 'jest-mock-console/dist/index.js' {
  declare module.exports: $Exports<'jest-mock-console/dist'>;
}
declare module 'jest-mock-console/dist/setupTestFramework.js' {
  declare module.exports: $Exports<'jest-mock-console/dist/setupTestFramework'>;
}
declare module 'jest-mock-console/index' {
  declare module.exports: $Exports<'jest-mock-console'>;
}
declare module 'jest-mock-console/index.js' {
  declare module.exports: $Exports<'jest-mock-console'>;
}
